export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Experience } from "./Experience";
export { default as Feedbacks } from "./Feedbacks";
export { default as Hero } from "./Hero";
export { default as Loader } from "./Loader";
export { default as Navbar } from "./Navbar";
export { default as Tech } from "./Tech";
export { default as Works } from "./Works";
